// <auto-generated />
namespace Eve.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class OrderIgnoresNaturalKey : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(OrderIgnoresNaturalKey));
        
        string IMigrationMetadata.Id
        {
            get { return "201211080152283_OrderIgnoresNaturalKey"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
